enabled = true
skipHiddenEntityRendering = true
#
#Range: 0.0 ~ 128.0
skipHiddenEntityRenderingSize = 3.0
#
#Range: 0.0 ~ 128.0
skipHiddenEntityRenderingDiff = 16.0
skipHiddenEntityRenderingBlacklist = []
skipHiddenTileEntityRendering = true
#
#Range: 0.0 ~ 128.0
skipHiddenTileEntityRenderingSize = 3.0
#
#Range: 0.0 ~ 128.0
skipHiddenTileEntityRenderingDiff = 16.0
skipHiddenTileEntityRenderingBlacklist = []

